<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Revenue by flight</title>
</head>
<body>

<%@ page import ="java.sql.*" %> 
<p style="float: right;"><a href="AdminLogout.jsp">Log out</a></p>

<% 
    ApplicationDB db = new ApplicationDB();	
	Connection con = db.getConnection();	
	Statement stmt = con.createStatement();
	ResultSet rs1;

	String airlineid = request.getParameter("airline_id");
   	String aircraftid = request.getParameter("ticket_id");
	
	rs1 = stmt.executeQuery("select sum(total_fare) as total_revenue from tickets where line_id= '"+airlineid+"' and ticket_num= '"+aircraftid+"' ");	
	
	out.println("Sales Revenue generated by flight " +airlineid + " " + aircraftid+ " is:");
	 
	while(rs1.next()){
		   out.println("$"+ rs1.getString("total_revenue"));
	%>
	<br>
	<%} %>


</body>
</html>