<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Revenue by Costumer</title>
</head>
<body>

<%@ page import ="java.sql.*" %> 
<p style="float: right;"><a href="AdminLogout.jsp">Log out</a></p>

<% 
    ApplicationDB db = new ApplicationDB();	
	Connection con = db.getConnection();	
	Statement stmt = con.createStatement();
	ResultSet rs1;

	String userid = request.getParameter("userid");
	
	rs1 = stmt.executeQuery("select sum(total_fare) + sum(booking_fee) as total_revenue from ticket where username= '"+userid+"' ");	
	
	out.println("Sales Revenue generated by user " +userid+ " is:");
	 
	while(rs1.next()){
		   out.println("$"+ rs1.getDouble("total_revenue")+ "0");
	%>
	<br>
	<%} %>

</body>
</html>