<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Admin Landing Page</title>
	</head>
	<body>
		
 		Welcome Admin
		<p style="float: right;"><a href="AdminLogout.jsp">Log out</a></p>
		<br>
		
		Add Information For:
			<form method="post" action="AdminAdd.jsp">
			  <input type="radio" name="command" value="rep"/>Customer Representative
			  <br>
			  <input type="radio" name="command" value="user"/>User
			  <br>
			  <input type="submit" value="Add" />
			</form>
			<br>


		<form action="AdminSalesReport.jsp" method="POST">
			Sales report for all tickets with PURCHASE DATE in the month of: 
		<br>**month format is 01=January, 12=December
		<br><input type="text" name="month" placeholder="Enter Month"> 
	
		
		<input type="submit" value="Retrieve">
			
	</form>
	
Retrieve list of all reservations by: 
<form action="AdminFlightReservations.jsp" method="POST">
	
	<br><input type="text" name="flightnum" placeholder="Enter Flight Number"> <input type="submit" value="Retrieve"> </form><br>
	<form action = "AdminFlightReservations.jsp" method = "post">
	
	<input type="text" name="user" placeholder="Enter User"> 
	
		<input type="submit" value="Retrieve">
	
</form>



<form action="AdminRevByAirline.jsp" method="POST">
	Revenue generated by airline: 
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"> 
	
	<form action="AdminRevByAirline.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminRevByCustomer.jsp" method="POST">
	Revenue generated by customer: 
	<br><input type="text" name="userid" placeholder="Enter Customer Username"> 
	
	<form action="AdminRevByCustomer.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>








<%
    
%>
</body>
</html>